[package]
name = "interop"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"

[dependencies]
quinn = { path = "../quinn" }
slog-term = "2"
structopt = "0.2.7"
tokio = "0.1.6"
tokio-current-thread = "0.1"
tokio-reactor = "0.1"
rustls = { version = "0.15", features = ["dangerous_configuration"] }
err-ctx = "0.2"
slog = "2.2"
futures-preview = { version = "0.3.0-alpha.11", features = ["compat"] }
webpki = "0.19"
